fix: Update dependency org.flywaydb:flyway-core to v10 (#153)
BREAKING CHANGE: Flyway 10.0.0 doesn't include Postgres plugin in the `core` artifact anymore

Whenever you provide another Flyway version via `jooqCodegen` configuration, make sure to include `org.flywaydb:flyway-database-postgresql` dependency in addition to `org.flywaydb:flyway-core`, otherwise you might get an error like this:
```
org.flywaydb.core.api.FlywayException: No database found to handle jdbc:postgresql://localhost:32798/postgres
```